### ISSUE TITLE
Selector interface support

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/reactive-react-redux#16]
Since many people are interested in the selector interface, I start thinking about it.

from there: https://github.com/dai-shi/react-hooks-easy-redux/issues/3#issuecomment-477992639

We shouldn't track the state usage in selectors. We don't need to track it if only the result is important.
That brings me an idea to provide another hook, which is much like something many have been discussing.

```javascript
const Pair = props => {
  const prevValue = useRef(null);
  const mapState = state => {
    const { value, name } = state[props.sliceId][props.pairId];
    const direction = value > prevValue.current ? "up" : "down";
    return { value, name, direction };
  };
  const { value, name, direction } = useReduxStateMapped(mapState);

  useEffect(() => {
    prevValue.current = value;
  });
  return (
```

It works somewhat magically. Closures are fine.

**Comment by dai-shi** [comment]
I'll push the implementation later. Meanwhile, here's the benchmark result.

### react-redux 7.0.0-beta.0

```
Results for benchmark stockticker:
┌─────────┬──────────────┬─────────────────────────────────────────────────────────────────────────────────────┐
│ Avg FPS │ Render       │ FPS Values                                                                          │
│         │ (Mount, Avg) │                                                                                     │
├─────────┼──────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ 28.46   │ 415.6, 0.6   │ 27,30,25,31,23,38,33,21,27,26,32,35,25,32,27,30,25,30,25,33,31,27,29,25,32,24,20,20 │
└─────────┴──────────────┴─────────────────────────────────────────────────────────────────────────────────────┘
```

### `useReduxStateMapped`
```
Running benchmark stockticker-rher
    Checking max FPS... (30 seconds)

Results for benchmark stockticker-rher:
┌─────────┬──────────────┬─────────────────────────────────────────────────────────────────────────────────────┐
│ Avg FPS │ Render       │ FPS Values                                                                          │
│         │ (Mount, Avg) │                                                                                     │
├─────────┼──────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ 22.77   │ 380.0, 0.5   │ 21,19,28,22,26,21,25,28,23,25,19,26,21,26,19,26,27,18,22,16,22,21,19,24,20,23,26,26 │
└─────────┴──────────────┴─────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by faceyspacey** [comment]
I guess closures are not an issue in a proxy-based world, re: @epeli 

regarding the FPS, they used to be 45 and 51 FPS for the react-redux 7 benchmark. I guess your computer is running slower. So that said, your version seems to be closing the gap, and solving the stockticker problem, nicely done!

**Comment by faceyspacey** [comment]
One thing I would look at is this:

- how many times is `Pair` rendering when `${c.UPDATE_PAIR}_${sliceId}` is dispatched?

How many times is the corresponding `render` function called in the react-redux 7 benchmark?

It's possible that the state change causes both `Slice` + `Pair` to render, and only one is necessary. I might not know the code well enough. But my intuition points to this being the difference. RHER currently isn't smart enough to cancel re-rendering the child, but somehow react-redux is in how it handles top-down rendering. In other words, if you know a subscription is from a child, don't notify it if the parent is already rendering.

Maybe this doesn't apply. I'm just giving what insight I know from studying react-redux in the past.

**Comment by faceyspacey** [comment]
You can make it faster by not doing closures. **Because then you can memoize the arguments** like in `react-redux` + `reselect`. 

So here's what you want it to look like:

```js
const mapState =(state, sliceId, pairId) => {
    const { value, name } = state[sliceId][pairId];
    const direction = value > prevValue.current ? "up" : "down";
    return { value, name, direction };
  };

const Pair = props => {
  const prevValue = useRef(null);
  const { value, name, direction } = useReduxStateMapped(mapState, props.sliceId, props.pairId);
 // or more like the deps array api being used in many places by React:
 const { value, name, direction } = useReduxStateMapped(mapState, [props.sliceId, props.pairId]);
```

Notice 2 things:
- we are being told the arguments. therefore we can compare their values to the previous args (if it's an object argument, do `shallowEqual` on the whole argument)
- we are passing a reference of `mapState`. This allows you to memoize (or better, cache) under the hood like this:

```js
const useReduxStateMapped = (mapState, deps) => {
  // work related to proxyequal access tracking

  // if state paths accessed, fallback to selector caching/memoization
  return useMemo(func, deps)
}
```

Using @theKashey 's [kashe](https://github.com/theKashey/kashe) you can cache *multiple* values rather than memoize a *single* value. That enables the selector be used in multiple places/components.

**Comment by faceyspacey** [comment]
Ultimately, `useMemo` solves similar problems to `re-reselect` but in a more automated way. React's new rendering architecture allows hooks to be linked nicely to runtime instances of components, right. If we could use that mechanism, we no longer need references to our selector functions. Instead we can just assume we are being passed the same one *as the last time the component function rendered.*

The problem, as I mentioned, is we need to be able to locate this memoized function in response to store updates. Maybe all we need to do is store a reference to it, which we can look into when the store subscription sends a notification.

**Comment by theKashey** [comment]
We need a short and clear example to optimize. 
There are two different things we are talking about:
- some changes on code level. How we might do things
- changes to the code structure/style. Which we could not control.

Which we could not control? What if create a new linting rule, which would do something we want, like a new react-hooks linting. But it's still a open question - what we want to do.

There is an idea - life outside of react, and be happy.
There is another idea - life inside component and be happy.

There is a need - to bailout if state change is not driving view change

__There is a bug__ - if you will pass down to a children some "object"/"array" - you will pass a `proxy`-ed version of it. (there is a method, deproxify, to unwrap objects). We need injections on `createElement` level, or even on `return` level to perform this operation.
Selectors also would be a great place to `deproxy`.

-----
We need to clarify what we actually need, and what is good to have.

**Comment by faceyspacey** [comment]
bro, i dont understand you

**Comment by dai-shi** [comment]
There seems various subjects in this topic, but let me ask one thing at the beginning.

As I implement useReduxStateMapped #17, I see no need to proxify the result for mapState.
What do you think?
@theKashey

**Comment by theKashey** [comment]
You still have to properly memoize internals of `mapState` to pass `shallowEqual` comparison, while this is where common redux applications sucks.
You might try to wrap `mapState` with `memoize-state`(library idea was to "fix" mapStateToProps) to transparently (for you) memoize it as a whole.

**Comment by faceyspacey** [comment]
so basically @dai-shi he's saying that `memoize-state` has proxyequal access checking built-in, so by using it you don't have to do the same work here. 

But I think you still have to confirm the selector was even used. If the component function doesn't call the selector, there's no point in triggering a re-render.

**Comment by dai-shi** [comment]
> You still have to properly memoize internals of mapState to pass shallowEqual comparison.

Oh, yeah. I totally miss that part. Let me take some time thinking about it.

**Comment by faceyspacey** [comment]
you can't accept props in closures for memoization. You need to accept them as arguments, which you can accept in a similar api to the `dependencies` arrays used elsewhere by the new React apis. 

```js
useReduxStateMapped(mapState, [arg1, arg2])
```

We can at least do the work of passing the args to `mapState`. It's a bit different than the React APIs where the args are not args, but solely dependencies. But in our case, it also reduces duplication: i.e. u dont have to pass the args twice like this:

```js
useReduxStateMapped((state) => mapState(state, arg1, arg2), [arg1, arg2])
```

**Comment by dai-shi** [comment]
> But I think you still have to confirm the selector was even used.

Yeah, I see this is necessary for Respond Framework. 🤔

**Comment by dai-shi** [comment]
> conditionally not use a selector u already started to use

Is the condition from props?
```javascript
const Pair = props => {
  const { a } = useReduxStateMapped(...);
  const value = props.b ? a : props.c;
  ...
};
```
Something like this? Yeah, this could happen.
(My recent commit e5d3c40 should cover this. Still experimenting.)

Any other case without props??

**Comment by faceyspacey** [comment]
Exactly

**Comment by dai-shi** [comment]
My current implementation of `useReduxStateMapped` has several issues: (1) there is no performance benefit. (2) it doesn't yet work without external memoization. (3) it can't deal well with multiple selectors/conditional usage.

All right, let me start over. Please be patient. The good news is now that I have better understanding of your requirement.

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/reactive-react-redux/v/2.0.0
Please give it a try. @faceyspacey

**Comment by theKashey** [comment]
🚀
