### ISSUE TITLE
Question: Ease of gradual transition to hooks concern

### ISSUE THREAD

**Issue by andrevinsky** [dai-shi/reactive-react-redux#24]
@dai-shi, et al., let me express concern on lack of information on transition support (from react-redux to reactive-react-redux). 

Scenario: I am currently developing and maintaining a rather large client-side application with centralized store managed by redux. With all this new fuzz like hooks and what not, I tend to want to write new components using the new technology elements. However, I want to leave working parts, especially the very basal parts, like the application root nodes as much intact as possible, that's one. Also, I want to be able to share an existing redux's store onto the `reactive-react-redux` goodies. Expecting that `useReduxDispatch` would produce me the same `dispatch()` function as `react-redux`'s `connect()` does.

This can be achievable either by using the same Redux provider (as in react-redux) - or exposing the package's own `connect()` function what would fallback to react-redux functionality.

I don't want to have duplicated stores, or partially split stores (between hooks supporting components and the older ones). Or nesting provider components. Or anything of the sort.

Thoughts?

**Comment by dai-shi** [comment]
Hi @andrevinsky , thanks for bringing up a discussion.

At this point, my proposal is to use "nesting provider components" which you said you don't want, though. This is a similar approach to the official react-apollo and the unofficial react-apollo-hooks, by the way.

```javascript
import { createStore } from 'redux';
import { Provider } from 'react-redux';
import { ReduxProvider } from 'reactive-react-redux';

const store = createStore(...);

const App = () => (
  <Provider store={store}>
    <ReduxProvider store={store}>
      ...
    </ReduxProvider>
  </Provider>
);
```

`useReduxDispatch` returns the bare `dispatch` as you expect.

Now, I would like to learn what would be a technical and mental barrier with this pattern.
Could you elaborate why you don't want this pattern?

**Comment by dai-shi** [comment]
```javascript
import { Provider as OrigProvider } from 'react-redux';
import { ReduxProvider } from 'reactive-react-redux';

const Provider = ({ store, children }) => (
  <OrigProvider store={store}>
    <ReduxProvider store={store}>
      {children}
    </ReduxProvider>
  </OrigProvider>
);
```

This may or may not ease the transition.

**Comment by dai-shi** [comment]
It's a bit different point, but reactive-react-redux v4.0.0-beta.0 (currently the `next` tag) have similar API to react-redux hooks. So, you can easily make transition from react-redux hooks to reactive-react-redux.

Closing this unless we have further discussion. Feel free to reopen.
