### ISSUE TITLE
'Please use <TrackedState...>' exception. Need help!

### ISSUE THREAD

**Issue by litari** [dai-shi/reactive-react-redux#35]
I'm getting the error and my page crashes. It appears that it is the `get state(){` error that is being thrown.

I haven't quite managed to track down what piece of my code it is that is causing it, but it seems to be some dispatch.

What do these exception-messages even mean?

`const warningObject = {
  get state() {
    console.trace();
    throw new Error('Please use <TrackedProvider ...>');
  },
  get dispatch() {
    throw new Error('Please use <TrackedProvider ...>');
  },
  get subscribe() {
    throw new Error('Please use <TrackedProvider ...>');
  },
};
`

**Comment by dai-shi** [comment]
Related to #34? There must be something I'm not aware of.
I need your help to dig into it.

Looks like you are not using the latest version.
Would you create a small example to reproduce the issue?
If you can use the latest version (with breaking change), let's merge the discussion to #34.

**Comment by litari** [comment]
I've tried updating the package to the latest version, but it still crashes.

I'm not sure if I'll be able to reproduce it small-scale since I don't know what exactly is causing the issue.

I can watch discussion #34 for now. I will let you know if I find anything on my own

**Comment by dai-shi** [comment]
Hm, the `<TrackedProvider ...>` is from the older version.
Maybe, you have two version mixed in your `node_modules`?

**Comment by litari** [comment]
I found a workaround. The problem for me was a useSelector in a memoized component, so my solution was to move the useSelector and pass the value as a prop.

Not sure why it would matter, but that fixed the problem for me.

**Comment by dai-shi** [comment]
> The problem for me was a useSelector in a memoized component,

Interesting... So, it might be able to reproduce it in a small app.
How does the memoized component look like? Is it React.memo, useMemo, or something else?

**Comment by dai-shi** [comment]
Hm, I wasn't able to reproduce the error.
https://codesandbox.io/s/reactive-react-redux-example-xvwf5
