### ISSUE TITLE
useTrackedState on an array does not trigger a rerender of FlatList with the extraData prop

### ISSUE THREAD

**Issue by shamilovtim** [dai-shi/reactive-react-redux#36]
Grabbing large array from state with tons of nested objects inside of it:

```
const trackingBoardList = useTrackedState<iAppState>().trackingBoardAndSchedule.trackingBoardList;
```

Then passing this to the ExtraData prop of FlatList 

```
 <FlatList extraData={trackingBoardList} />
```

In the docs, FlatList is supposed to re-render when extraData detects a change. FlatList does not re-render with useTrackedState. Side note: nowhere in the RN Flatlist docs is it specified that extraData must be a primitive. That being said, if I try to track the .length of my array it does work (but obviously only when the amount of array elements change, not when the objects inside the array have changed properties).

**Comment by dai-shi** [comment]
Thanks for reporting!

https://facebook.github.io/react-native/docs/flatlist.html#extradata
> A marker property for telling the list to re-render (since it implements PureComponent). If any of your renderItem, Header, Footer, etc. functions depend on anything outside of the data prop, stick it here and treat it immutably.

Because it is a marker property, I understand the state **is not used**.
If it is not used, we can't track the usage by Proxy.

If I use `data` instead, it works.
I made an example in expo snack.
https://snack.expo.io/H1tgmiKIS

<details>
<summary>code</summary>

./App.js
```jsx
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';
import { createStore } from 'redux';
import { Provider } from 'reactive-react-redux';

import FlatListExample from './components/FlatListExample';

const initialState = {
  data: {
    items: [
      { key: 1, name: 'aaa' },
      { key: 2, name: 'bbb' },
      { key: 3, name: 'ccc' },
    ],
  },
};

const reducer = (state = initialState, action) => {
  switch (action.type) {
    case 'rename':
      return {
        ...state,
        data: {
          ...state.data,
          items: state.data.items.map(item =>
            item.key === 2
              ? {
                  ...item,
                  name: item.name + 'x',
                }
              : item
          ),
        },
      };
    default:
      return state;
  }
};

const store = createStore(reducer);

const App = () => (
  <Provider store={store}>
    <View>
      <FlatListExample />
    </View>
  </Provider>
);

export default App;
```

./components/FlatListExample.js
```jsx
import * as React from 'react';
import { Text, View, FlatList, TouchableOpacity } from 'react-native';
import { useDispatch, useTrackedState } from 'reactive-react-redux';

const FlatListExample = () => {
  const state = useTrackedState();
  const items = state.data.items;
  const dispatch = useDispatch();
  const onPress = () => dispatch({ type: 'rename' });
  return (
    <View style={{ marginVertical: 100 }}>
      <FlatList
        data={items}
        renderItem={({ item }) => (
          <View>
            <Text>{item.name}</Text>
          </View>
        )}
      />
      <TouchableOpacity onPress={onPress}>
        <Text>Rename 2nd item</Text>
      </TouchableOpacity>
    </View>
  );
};

export default FlatListExample;
```

</details>

Please check it out.

If you need to specify `extraData` for a certain purpose, you could use `useSelector` instead of `useTrackedState`.
This is unfortunate though.

**Comment by dai-shi** [comment]
Okay, I misunderstood something in my previous comment.

>  I understand the state is not used.

The `extraData` itself is used. So, it should work.

Here's the updated snack.
https://snack.expo.io/B1QHJ2FIS

It seems working.

@shamilovtim Can you modify the example to reproduce your issue?

**Comment by shamilovtim** [comment]
Thanks so much for your response @dai-shi. This is not a problem with the library. I discovered that the issue was in the way I was using ImmerJS for immutability. It was working on some 10+ screens of my application but it broke here and it was very difficult to debug. I appreciate your taking the time to respond and this is a really awesome library I'm using in my project.

**Comment by dai-shi** [comment]
Good to hear that.
