### ISSUE TITLE
getUntrackedObject always returning null

### ISSUE THREAD

**Issue by bostondv** [dai-shi/reactive-react-redux#45]
When using the recommended pattern `getUntrackedObject` to avoid using the proxied state outside render I'm finding the `getUntrackedObject` always returns null.

Contrived example:

```
const MyComp = () => {
  const state = useTrackedState()
  const dispatch = useDispatch()

  return (
    <button onClick={() => dispatch({ type: 'FOO', value: getUntrackedObject(state) })}>
      Update
    </button>
  )
}
```

Tracing through [the method](https://github.com/dai-shi/reactive-react-redux/blob/7c2e705930e6cca2eab33b60864d840c4e10c532/dist/deepProxy.js#L189), I'm finding that `isPlainObject(obj)` returns true, but the `obj[GET_ORIGINAL_SYMBOL]` returns `undefined` and thus causes the method to return null rather than the untracked object.

Not sure if this is a bug or if I may be mis-using it somehow?

**Comment by dai-shi** [comment]
Thanks for trying. The implementation is intentional: `getUntrackedObject` returns `null` if the object is not proxied.
You could implement a helper function.
```js
const getUntrackedObjectIfTracked = (obj) => getUntrackedObject(obj) || obj;
```

That said, there can be a bug. Could you reproduce the behavior you found?
I did try it, but it seems working. 👉 https://codesandbox.io/s/condescending-night-2ctbc (Person.tsx L14)

**Comment by bostondv** [comment]
Thanks for setting up that sandbox. In our app (where there may be other factors at play) its not working but I see its working here. In our app the state I'm passing into the function is a Proxy, so it should be returning the plain object. 

Being a more complex scenario my best guess right now its exposing a bug this simpler example is not or there's something else wrong in our app. I'll try to reproduce the behavior in the sandbox and post my findings!

**Comment by bostondv** [comment]
FWIW I haven't been able to reproduce it yet in the sandbox. We use immer and a custom context that we compose into a custom hook. I've roughly replicated here https://codesandbox.io/s/objective-jones-6fnin, but all seems to be working well. Still digging...
