### ISSUE TITLE
SSR and `useLayoutEffect` issues warning in dev mode

### ISSUE THREAD

**Issue by JackCA** [dai-shi/reactive-react-redux#47]
The recent change in [`v4.6.0`](https://github.com/dai-shi/reactive-react-redux/commit/a463d82742ea413830c51600c5b51a2c05a40403) will result in the following warning in an SSR rendered app in development:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
    in Provider (at _app.tsx:188)
```

I think you should be able to add another condition in the new condition checking whether `typeof window === 'undefined'`

**Comment by dai-shi** [comment]
Nice catch! I will make a fix.

**Comment by dai-shi** [comment]
Published https://www.npmjs.com/package/reactive-react-redux/v/4.6.1
Thanks for your help!
